name: 'Pros Depot from Releases'
description: 'Generates a depot json from GitHub Releases and places it in the desired repo.'
author: 'LemLib'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'archive'
  color: 'yellow'

# Define your inputs here.
inputs:
  repo:
    description: |
      Repository to which the depot will be pushed to.
      If source-repo is not defined, then this parameter will be assumed to be the source repo.
      If left undefined, then this parameter will be inferred from the workflow that called this action.
      example: "lemlib/lemlib"
    required: false
  
  source-repo:
    description: |
      Repository from which to retrieve releases from
      If left undefined, then the repo parameter will be assumed to be the source repo.
      example: "lemlib/lemlib"
    required: false

  token:
    description: 'Your GitHub Access Token. Necessary to not get rate limited.'
    required: true
    default: ${{ github.token }}  

  branch:
    description: 'The branch where the stable depot json will be placed.'
    required: true
    default: 'depot'

  pre-release-branch:
    description: |
      The branch of the depot where pre release versions should be placed. 
      If omitted, then the pre-release versions will not be placed in a depot.
    required: false
    default: 'depot'

  path:
    description: 'The path to the stable depot json.'
    required: true
    default: 'stable.json'

  pre-release-path:
    description: | 
      The path to the depot where pre release versions should be placed. 
      If omitted, then the pre-release versions will not be placed in a depot. 
      If pre-release-branch == branch AND pre-release-path == path,
      then the pre-release versions will be placed in the same depot as the stable versions.

      If pre-release-branch is not defined, then this input will be ignored.
    required: false
    default: 'beta.json'

  readable-json:
    description: 'Whether the depot json should be formatted to be human readable (true/false).'
    required: true
    default: false

  message:
    description: 'The commit message that will be used when updating the depot'
    required: false

  quiet:
    description: 'When true, all warnings will be silenced. Errors should still be logged.'
    required: false
    default: false

  ignore-non-template-assets:
    description: 'When true, silences warnings regarding assets that do not contain a template.pros file.'
    required: false
    default: false 
runs:
  using: node20
  main: dist/index.js
