name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  repo:
    description: 'The string represetation of the repo name (eg: lemlib/lemlib)'
    required: false

  github_token:
    description: 'Your GitHub Access Token. Necessary to not get rate limited.'
    required: true
    default: ${{ github.token }}  

  branch:
    description: 'The branch you want to put the depot json on.'
    required: true
    default: 'depot'

  path:
    description: 'The path to the depot json.'
    required: true
    default: 'depot.json'

  readable-json:
    description: 'Whether the depot json should be formatted to be human readable (true/false).'
    required: true
    default: false

  messsage:
    description: 'The commit message for the new commit depot json.'
    required: false

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
