import { Octokit } from '@octokit/rest'
import { Depot, DepotEntry, DepotLocation } from './types'
import { homepage as actionURL } from '../package.json'

function jsonToDepot(json: string): Depot {
  return JSON.parse(json)
}

async function getOldDepot(
  location: DepotLocation,
  client: Octokit
): Promise<Depot> {
  const res = await client.repos.getContent({
    ...location,
    ref: location.branch
  })
  const json = res.data.toString()
  return jsonToDepot(json)
}

function depotEntryIsEqual(temp1: DepotEntry, temp2: DepotEntry): boolean {
  return (
    (['version', 'name', 'supported_kernels', 'target'] as const).every(
      key => temp1[key] === temp2[key]
    ) && temp1.metadata.location === temp2.metadata.location
  )
}

/**
 * Adds gitmoji and explains that the commit is the result of automation
 * @param message
 * @returns
 */
function formatCommitMessage(message: string): string {
  const gitmoji = ':bookmark:'
  const automationMessage = `This commit was generated by an automated workflow: ${actionURL}`
  return `${gitmoji} message \n\n${automationMessage}`
}

export async function createCommitMessage(
  newJson: string,
  location: DepotLocation,
  client: Octokit
): Promise<string> {
  return formatCommitMessage(await createRawMessage(newJson, location, client))
}

async function createRawMessage(
  newJson: string,
  location: DepotLocation,
  client: Octokit
): Promise<string> {
  const oldDepot = await getOldDepot(location, client)
  const newDepot = jsonToDepot(newJson)

  const changedTemplates: DepotEntry[] = []
  for (const template of newDepot) {
    if (
      !oldDepot.some(oldTemplate => depotEntryIsEqual(template, oldTemplate))
    ) {
      changedTemplates.push(template)
    }
  }

  if (changedTemplates.length === 1) {
    if (
      oldDepot.some(
        oldTemplate => oldTemplate.version == changedTemplates[0].version
      )
    )
      return `Update ${changedTemplates[0].version}`
    else return `Add ${changedTemplates[0].version}`
  }
  if (changedTemplates.length > 1) return 'Update multiple versions'
  return 'Update depot'
}
